version: '3.8'

services:
  # AI Fitness Assistant Backend
  fitness-backend:
    build: 
      context: .
      dockerfile: Dockerfile.fitness-backend
    container_name: fitness-backend
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
    networks:
      - fitness-network
    volumes:
      - ./logs:/app/logs

  # AI Fitness Assistant Frontend
  fitness-frontend:
    build:
      context: .
      dockerfile: Dockerfile.fitness-frontend
    container_name: fitness-frontend
    restart: unless-stopped
    networks:
      - fitness-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - fitness-network
    depends_on:
      - fitness-backend
      - fitness-frontend

  # Cloudflare Tunnel
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - fitness-network
    depends_on:
      - nginx

networks:
  fitness-network:
    driver: bridge

volumes:
  logs: 